server:
  port: 8088
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useSSL=false
      username: DES@M5blq4GyNdJn5A/fQ+tk+w==
      password: DES@iLW/EHruBCaPpNZGoY/DOQ==
#可以用data.name表示
data:
  name: "你好"
  age:  30
  gender: 男
